# MySQL database connection
connection:
  host: {{dbHost}}
  port: {{dbPort}}
  database: {{dbName}}
  user: {{dbUsername}}
  password: {{dbPassword}}
  charset: utf8mb4
  logging: false

migrations:
  automatic: true

# How often the server uptime log is updated
boot_history:
  update_frequency: 15 secs # Minimum is 10 seconds
